[package]
name = "vendor-unifi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
delve-core.workspace = true
async-trait.workspace = true
inventory.workspace = true
reqwest.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
url.workspace = true

[dev-dependencies]
delve-plugin-testkit.workspace = true
tokio.workspace = true
sha2.workspace = true
