[package]
name = "delve-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "delve"
path = "src/main.rs"

[dependencies]
delve-core.workspace = true
delve-store-sqlite = { path = "../delve-store-sqlite" }
subscriber-webhook = { path = "../delve-subscribers/subscriber-webhook", optional = true }
subscriber-email = { path = "../delve-subscribers/subscriber-email", optional = true }
vendor-cisco = { path = "../delve-vendors/vendor-cisco", optional = true }
vendor-unifi = { path = "../delve-vendors/vendor-unifi", optional = true }

tokio.workspace = true
clap.workspace = true
anstream.workspace = true
anstyle.workspace = true
toml.workspace = true
dirs.workspace = true
serde.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
anyhow.workspace = true
sha2.workspace = true
dialoguer.workspace = true
url.workspace = true

[features]
default = []
vendor-cisco = ["dep:vendor-cisco"]
vendor-unifi = ["dep:vendor-unifi"]
subscriber-webhook = ["dep:subscriber-webhook"]
subscriber-email = ["dep:subscriber-email"]
all-vendors = ["vendor-cisco", "vendor-unifi"]

[dev-dependencies]
async-trait.workspace = true
serde_json.workspace = true
chrono-tz.workspace = true
